export const SITE_ID_REQUEST = 'SITE_ID_REQUEST';
export const SITE_ID_SUCCESS = 'SITE_ID_SUCCESS';
export const SITE_ID_FAIL = 'SITE_ID_FAIL';

export const ALL_TABLE_REQUEST = 'ALL_TABLE_REQUEST';
export const ALL_TABLE_SUCCESS = 'ALL_TABLE_SUCCESS';
export const ALL_TABLE_FAIL = 'ALL_TABLE_FAIL';

export const UNIQUE_TABLE_REQUEST = 'UNIQUE_TABLE_REQUEST';
export const UNIQUE_TABLE_sUCCESS = 'UNIQUE_TABLE_sUCCESS';
export const UNIQUE_TABLE_FAIL = 'UNIQUE_TABLE_FAIL';

export const SITE_ENGINEER_FOR_SITE_REQUEST = 'SITE_ENGINEER_FOR_SITE_REQUEST';
export const SITE_ENGINEER_FOR_SITE_SUCCESS = 'SITE_ENGINEER_FOR_SITE_SUCCESS';
export const SITE_ENGINEER_FOR_SITE_FAIL = 'SITE_ENGINEER_FOR_SITE_FAIL';
