export const SITE_ID_REQUEST = 'SITE_ID_REQUEST';
export const SITE_ID_SUCCESS = 'SITE_ID_SUCCESS';
export const SITE_ID_FAIL = 'SITE_ID_FAIL';

export const ALL_TABLE_REQUEST = 'ALL_TABLE_REQUEST';
export const ALL_TABLE_SUCCESS = 'ALL_TABLE_SUCCESS';
export const UNIQUE_TABLE_sUCCESS = 'UNIQUE_TABLE_sUCCESS';
export const ALL_TABLE_FAIL = 'ALL_TABLE_FAIL';
