export const HUAWEI_DATABASE_REQUEST = 'HUAWEI_DATABASE_REQUEST';
export const HUAWEI_DATABASE_SUCCESS = 'HUAWEI_DATABASE_SUCCESS';
export const HUAWEI_DATABASE_FAIL = 'HUAWEI_DATABASE_FAIL';

//------------------------------

export const HUAWEI_FILTERED_NAMES_REQUEST = 'HUAWEI_FILTERED_NAMES_REQUEST';
export const HUAWEI_FILTERED_NAMES_SUCCESS = 'HUAWEI_FILTERED_NAMES_SUCCESS';
export const HUAWEI_FILTERED_NAMES_FAIL = 'HUAWEI_FILTERED_NAMES_FAIL';

//----------------------------

export const HUAWEI_COLUMN_CHART_DATA_REQUEST = 'HUAWEI_COLUMN_CHART_DATA_REQUEST';
export const HUAWEI_COLUMN_CHART_DATA_SUCCESS = 'HUAWEI_COLUMN_CHART_DATA_SUCCESS';
export const HUAWEI_COLUMN_CHART_DATA_FAIL = 'HUAWEI_COLUMN_CHART_DATA_FAIL';

//----------------------------

export const HUAWEI_AREA_CHART_DATA_REQUEST = 'HUAWEI_AREA_CHART_DATA_REQUEST';
export const HUAWEI_AREA_CHART_DATA_SUCCESS = 'HUAWEI_AREA_CHART_DATA_SUCCESS';
export const HUAWEI_AREA_CHART_DATA_FAIL = 'HUAWEI_AREA_CHART_DATA_FAIL';

//-----------------------------

export const HUAWEI_SCOPE_DATA_REQUEST = 'HUAWEI_SCOPE_DATA_REQUEST';
export const HUAWEI_SCOPE_DATA_SUCCESS = 'HUAWEI_SCOPE_DATA_SUCCESS';
export const HUAWEI_SCOPE_DATA_FAIL = 'HUAWEI_SCOPE_DATA_FAIL';

//-----------------------------

export const HUAWEI_LAST_UPDATE_REQUEST = 'HUAWEI_LAST_UPDATE_REQUEST';
export const HUAWEI_LAST_UPDATE_SUCCESS = 'HUAWEI_LAST_UPDATE_SUCCESS';
export const HUAWEI_LAST_UPDATE_FAIL = 'HUAWEI_LAST_UPDATE_FAIL';
