export const MOBITEL_DATABASE_REQUEST = 'MOBITEL_DATABASE_REQUEST';
export const MOBITEL_DATABASE_SUCCESS = 'MOBITEL_DATABASE_SUCCESS';
export const MOBITEL_DATABASE_FAIL = 'MOBITEL_DATABASE_FAIL';
//----------------------------

export const MOBITEL_OVERVIEW_REQUEST = 'MOBITEL_OVERVIEW_REQUEST';
export const MOBITEL_OVERVIEW_SUCCESS = 'MOBITEL_OVERVIEW_SUCCESS';
export const MOBITEL_OVERVIEW_FAIL = 'MOBITEL_OVERVIEW_FAIL';

//-----------------------------

export const MOBITEL_CHART_COLUMN_DATA_REQUEST = 'MOBITEL_CHART_COLUMN_DATA_REQUEST';
export const MOBITEL_CHART_COLUMN_DATA_SUCCESS = 'MOBITEL_CHART_COLUMN_DATA_SUCCESS';
export const MOBITEL_CHART_COLUMN_DATA_FAIL = 'MOBITEL_CHART_COLUMN_DATA_FAIL';

//-----------------------------

export const MOBITEL_CHART_AREA_DATA_REQUEST = 'MOBITEL_CHART_AREA_DATA_REQUEST';
export const MOBITEL_CHART_AREA_DATA_SUCCESS = 'MOBITEL_CHART_AREA_DATA_SUCCESS';
export const MOBITEL_CHART_AREA_DATA_FAIL = 'MOBITEL_CHART_AREA_DATA_FAIL';

//----------------------------

export const MOBITEL_SCOPE_DATA_REQUEST = 'MOBITEL_SCOPE_DATA_REQUEST';
export const MOBITEL_SCOPE_DATA_SUCCESS = 'MOBITEL_SCOPE_DATA_SUCCESS';
export const MOBITEL_SCOPE_DATA_FAIL = 'MOBITEL_SCOPE_DATA_FAIL';

//------------------------------

export const MOBITEL_LAST_UPDATE_REQUEST = 'MOBITEL_LAST_UPDATE_REQUEST';
export const MOBITEL_LAST_UPDATE_SUCCESS = 'MOBITEL_LAST_UPDATE_SUCCESS';
export const MOBITEL_LAST_UPDATE_FAIL = 'MOBITEL_LAST_UPDATE_FAIL';
