export const ZTE_DATABASE_REQUEST = 'ZTE_DATABASE_REQUEST';
export const ZTE_DATABASE_SUCCESS = 'ZTE_DATABASE_SUCCESS';
export const ZTE_DATABASE_FAIL = 'ZTE_DATABASE_FAIL';

//------------------------------

export const ZTE_FILTERED_NAMES_REQUEST = 'ZTE_FILTERED_NAMES_REQUEST';
export const ZTE_FILTERED_NAMES_SUCCESS = 'ZTE_FILTERED_NAMES_SUCCESS';
export const ZTE_FILTERED_NAMES_FAIL = 'ZTE_FILTERED_NAMES_FAIL';

//-----------------------------

export const ZTE_COLUMN_CHART_DATA_REQUEST = 'ZTE_COLUMN_CHART_DATA_REQUEST';
export const ZTE_COLUMN_CHART_DATA_SUCCESS = 'ZTE_COLUMN_CHART_DATA_SUCCESS';
export const ZTE_COLUMN_CHART_DATA_FAIL = 'ZTE_COLUMN_CHART_DATA_FAIL';

//-----------------------------
export const ZTE_AREA_CHART_DATA_REQUEST = 'ZTE_AREA_CHART_DATA_REQUEST';
export const ZTE_AREA_CHART_DATA_SUCCESS = 'ZTE_AREA_CHART_DATA_SUCCESS';
export const ZTE_AREA_CHART_DATA_FAIL = 'ZTE_AREA_CHART_DATA_FAIL';

//------------------------------
export const ZTE_SCOPE_DATA_REQUEST = 'ZTE_SCOPE_DATA_REQUEST';
export const ZTE_SCOPE_DATA_SUCCESS = 'ZTE_SCOPE_DATA_SUCCESS';
export const ZTE_SCOPE_DATA_FAIL = 'ZTE_SCOPE_DATA_FAIL';

//----------------------------

export const ZTE_LAST_UPDATE_REQUEST = 'ZTE_LAST_UPDATE_REQUEST';
export const ZTE_LAST_UPDATE_SUCCESS = 'ZTE_LAST_UPDATE_SUCCESS';
export const ZTE_LAST_UPDATE_FAIL = 'ZTE_LAST_UPDATE_FAIL';
